language: c
compiler: gcc
sudo: false
cache: ccache

jobs:
  include:
    - name: Windows
      os: windows
      before_install:
        - choco install python --version=3.5.4
      env:
        - PATH=/c/Python35:/c/Python35/Scripts:$PATH
      script:
        - echo "$PATH"
        - ls -l /c/Python35 /c/Python35/Scripts
        - type python; type python3; type python.exe; type python3.exe
        - python scripts/generate_psa_constants.py
        - sleep 5 # Give time for logs to catch up
        - scripts/windows_msbuild.bat v141 # Visual Studio 2017

after_failure:
- tests/scripts/travis-log-failure.sh

env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="
