language: c
compiler: gcc
sudo: false
cache: ccache
for x in $(ldd $(which gnutls-cli) $(which gnutls-serv) | sed -n 's!.* \(/[^ ]*\).*!\1!p' | sort -u); do dpkg -S $x; done | sed 's/: .*//' | xargs dpkg-query --showformat='${Package} ${Version}\n' --show
jobs:
  include:
    - name: gnutls test
      script:
        - export
        - COLUMNS=200 dpkg -l
        - make
        - tests/compat.sh -m tls1 -p GnuTLS -V NO

after_failure:
- tests/scripts/travis-log-failure.sh

env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="

addons:
  apt:
    packages:
    - gnutls-bin
  coverity_scan:
    project:
      name: "ARMmbed/mbedtls"
    notification_email: support-mbedtls@arm.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan
